on: [push]

name: runner-example

jobs:
  example:
    runs-on: gpu
    steps:
    - uses: actions/checkout@master
#    - uses: iterative/setup-cml@v1
    - name: train model
      run: |
          pip install --find-links /home/runner/cache --no-index tensorflow==2.12.0
          python gpudocker.py > report.md
          cml comment create --publish report.md
      env:
          REPO_TOKEN:  ${{ secrets.GITHUB_TOKEN }}
